# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 12:13
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articleinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='texts',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
